spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/javi"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Nguyen2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
