spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/javi"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Nguyen2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
javi:
  upload-file:
    base-uri: file:///D:/Javi-dictionary/upload/
api:
  prefix: /api/v1